### ISSUE TITLE
ERROR Nil is not a function

### ISSUE THREAD

**Issue by CMOISDEAD** [sayanarijit/preview-tabbed.xplr#2]
When I run :p I get this error, I have all the dependencies and the preview in nnn works
help :)

**Comment by justchokingaround** [comment]
how can i fix this error??

**Comment by sayanarijit** [comment]
Can you pls post a screenshot of the err?

**Comment by justchokingaround** [comment]
i forgot to copy a helper function from your config, which is why it didn't work, sorry, that's my bad :pensive: 

i do however have another question. is it not possible to get image preview inside a preview pane? without an external pane. it would be great if something like sixel or viu or imv is supported, but i don't think it is atm?
![image](https://user-images.githubusercontent.com/44473782/218095668-97c78ee0-518f-4f88-9b42-dcace92dd278.png)

**Comment by sayanarijit** [comment]
@emsquid is working on it https://github.com/emsquid/preview.xplr. They're active on xplr chatroom. Feel free to join discord/matrix.

**Comment by justchokingaround** [comment]
oh thats really nice, perfect :+1: great !!

**Comment by emsquid** [comment]
> oh thats really nice, perfect :+1: great !!

I created a cli tool to make that possible, but I didn't integrate it in my plugin yet, coming soon...

**Comment by sayanarijit** [comment]
Closing this.
